#ifndef CPS2000_ASSIGNMENT_TOKEN_H
#define CPS2000_ASSIGNMENT_TOKEN_H

using namespace std;

/*
 * Possible types of tokens that can be generated by the program
 */
enum TokenType {
    tREJECTED = 0,

    //Whitespace
    tSPACE,

    //Types
    tBOOLEAN,
    tFLOAT,
    tINTEGER,
    tSTRING,

    //Literals
    tFLOATLITERAL,
    tINTEGERLITERAL,
    tSTRINGLITERAL,

    //Boolean Literals
    tTRUE,
    tFALSE,

    //Identifier
    tIDENTIFIER,

    //OPERATORS
    tAND,
    tOR,
    tNOT,
    tASTERISK,
    tFSLASH,
    tPLUS,
    tMINUS,
    tLESSTHAN,
    tLESSTHANEQUAL,
    tGREATERTHAN,
    tGREATERTHANEQUAL,
    tEQUALASSIGN,
    tEQUALRELATIONAL,
    tNOTEQUAL,

    //Punctuation
    tCOMMA,
    tCOLON,
    tSEMICOLON,
    tLBRACKET,
    tRBRACKET,
    tLCURLY,
    tRCURLY,

    //Comment
    tCOMMENT,

    //Reserved Words
    tELSE,
    tFOR,
    tIF,
    tLET,
    tPRINT,
    tRETURN,
    tWHILE,

    //End of File
    tEND
};


class Token {
public:
    Token();
    Token(int lineNum, TokenType type);
    Token(int lineNum, TokenType type, string* value);

    string toString();
    string getTypeName();

    TokenType type;
    string value;
    int lineNum;
};


#endif // CPS2000_ASSIGNMENT_TOKEN_H
